routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Spatie\Activitylog\Models\Activity;

Route::get('/', function () {
    // return Activity::all();
    return view('Auth/login');
});
Route::group(['middleware' => 'checkuser'],function(){

Route::resource('sample', 'SampleController');
Route::post('sample/update', 'SampleController@update')->name('sample.update');

Route::get('/index', 'SampleController@index');
Route::get('sample/edit/{id}', 'SampleController@edit');
Route::get('sample/show/{id}', 'SampleController@show');
Route::get('sample/destroy/{id}', 'SampleController@destroy');
});
// login 

// Route::post('/main ', 'LoginController@index');
Route::post('/main/checklogin', 'LoginController@checklogin');
Route::get('main/successlogin ', 'LoginController@successlogin');
Route::get('main/logout ', 'LoginController@logout');

/*
 * Export Buy Record Excel
 */
Route::get('Userexport', 'ExportController@export')->name('Userexport');
Route::get('UserimportExportView', 'ExportController@importExportView');
Route::post('Userimport', 'ExportController@import')->name('Userimport');


// Test email
Route::get('email-test', array('as' => 'normindex', function(){
  
	$details['email'] = 'from@example.com';
  
    dispatch(new App\Jobs\SendEmailJob($details));
  
    return redirect('index');
}));


// test 
// Route::get('/index', function () {
//     return view('WD/index');
// });
Route::get('/login', function () {
    return view('Auth/login');
});
Route::get('/register', function () {
    return view('Auth/register');
});
Route::get('/pass', function () {
    return view('Auth/pass');
});

resources/views/WD/sample_data.blade.php
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRUD</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>
    @if(isset(Auth::user()->email))
    <div class="alert alert-danger success-block">
        <strong>Welcome {{Auth::user()-email}}</strong>
        <br/>
        <a href="{{url('/main/logout')}}">Logout</a>
    </div>
    else
    <script>window.location="/main";</script>
    @endif
    <!-- <div>
    <button class="btn btn-warning" >Logout</button>
    </div> -->
    <div class="container">
        <br />
        <h3 align="center">CRUD</h3>
        <br />
        <div align="right">
            <button type="button" name="create_record" id="create_record" class="btn btn-primary btn-sm">Create Record</button>
        </div>
        <br />
        <div class="table-responsive">
            <table id="user_table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th width="25%">Image</th>
                        <th width="25%">First Name</th>
                        <th width="25%">Last Name</th>
                        <th width="25%">Email</th>
                        <th width="30%">Action</th>
                    </tr>
                </thead>
            </table>
        </div>
        <br />
        <br />
    </div>
</body>

</html>

<div id="formModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add New User</h4>
            </div>
            <div class="modal-body">
                <span id="form_result"></span>
                <form method="post" id="sample_form" class="form-horizontal">
                    @csrf
                    <div class="form-group">
                        <label class="control-label col-md-4">Select Profile Image: </label>
                        <div class="col-md-8">
                            <input type="file" name="image" id="image" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4">user name: </label>
                        <div class="col-md-8">
                            <input type="text" name="user_name" id="user_name" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4">password: </label>
                        <div class="col-md-8">
                            <input type="password" name="password" id="password" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4">First Name : </label>
                        <div class="col-md-8">
                            <input type="text" name="first_name" id="first_name" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4">Last Name : </label>
                        <div class="col-md-8">
                            <input type="text" name="last_name" id="last_name" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4">Email: </label>
                        <div class="col-md-8">
                            <input type="text" name="email" id="email" class="form-control" />
                        </div>
                    </div>
                    <br />
                    <div class="form-group" align="center">
                        <input type="hidden" name="action" id="action" value="Add" />
                        <input type="hidden" name="hidden_id" id="hidden_id" />
                        <input type="submit" name="action_button" id="action_button" class="btn btn-warning" value="Add" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div id="confirmModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">Confirmation</h2>
            </div>
            <div class="modal-body">
                <h4 align="center" style="margin:0;">Are you sure you want to remove this data?</h4>
            </div>
            <div class="modal-footer">
                <button type="button" name="ok_button" id="ok_button" class="btn btn-danger">OK</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function() {

        $('#user_table').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: "{{ route('sample.index') }}",
            },
            columns: [
                {
                    data: 'image',
                    name: 'image',
                    render: function(data, type, full, meta){
                        return "<img src={{ URL::to('/')}}/images/"+ data + " width='70' class='img-thumbnail' />";
                    },
                    orderable: false
                },
                {
                    data: 'first_name',
                    name: 'first_name'
                },
                {
                    data: 'last_name',
                    name: 'last_name'
                },
                {
                    data: 'email',
                    name: 'email'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                }
            ]
        });

        $('#create_record').click(function() {
            $('.modal-title').text('Add New Record');
            $('#action_button').val('Add');
            $('#action').val('Add');
            $('#form_result').html('');
            $('#formModal').modal('show');
        });

        $('#sample_form').on('submit', function(event) {
            event.preventDefault();
            var action_url = '';

            if ($('#action').val() == 'Add') {
                // document.getElementById("action_button").display = block;
                action_url = "{{ route('sample.store') }}";
            }

            if ($('#action').val() == 'Edit') {
                // document.getElementById("action_button").display = block;
                action_url = "{{ route('sample.update') }}";
            }
            // else{document.getElementById("action_button").display = none;

            // }
            $.ajax({
                url: action_url,
                method: "POST",
                data: $(this).serialize(),
                dataType: "json",
                success: function(data) {
                    var html = '';
                    if (data.errors) {
                        html = '<div class="alert alert-danger">';
                        for (var count = 0; count < data.errors.length; count++) {
                            html += '<p>' + data.errors[count] + '</p>';
                        }
                        html += '</div>';
                    }
                    if (data.success) {
                        html = '<div class="alert alert-success">' + data.success + '</div>';
                        $('#sample_form')[0].reset();
                        $('#user_table').DataTable().ajax.reload();
                    }
                    $('#form_result').html(html);
                }
            });
        });

        $(document).on('click', '.edit', function() {
            document.getElementById("image").readOnly = false;
            document.getElementById("first_name").readOnly = false;
            document.getElementById("last_name").readOnly = false;
            document.getElementById("user_name").readOnly = false;
            document.getElementById("password").readOnly = false;
            document.getElementById("email").readOnly = false;
            document.getElementById("action_button").style.display = "inline";
            var id = $(this).attr('id');
            $('#form_result').html('');
            $.ajax({
                url: "/sample/edit/"+id,
                dataType: "json",
                success: function(data) {
                    $('#image').val(data.result.image);
                    $('#first_name').val(data.result.first_name);
                    $('#last_name').val(data.result.last_name);
                    $('#user_name').val(data.result.user_name);
                    $('#password').val(data.result.password);
                    $('#email').val(data.result.email);
                    $('#hidden_id').val(id);
                    $('.modal-title').text('Edit Record');
                    $('#action_button').val('Edit');
                    $('#action').val('Edit');
                    $('#formModal').modal('show');
                }
            })
        });

        $(document).on('click', '.detail', function() {
            document.getElementById("action_button").style.display = "none";
            // document.getElementById("action").style.display = "none";
            document.getElementById("image").readOnly = true;
            document.getElementById("first_name").readOnly = true;
            document.getElementById("last_name").readOnly = true;
            document.getElementById("user_name").readOnly = true;
            document.getElementById("password").readOnly = true;
            document.getElementById("email").readOnly = true;
            var id = $(this).attr('id');
            $('#form_result').html('');
            $.ajax({
                url: "/sample/show/"+id,
                dataType: "json",
                success: function(data) {
                    $('#image').val(data.result.first_name);
                    $('#first_name').val(data.result.first_name);
                    $('#last_name').val(data.result.last_name);
                    $('#user_name').val(data.result.user_name);
                    $('#password').val(data.result.password);
                    $('#email').val(data.result.email);
                    $('#hidden_id').val(id);
                    $('.modal-title').text('View Record');
                    $('#action_button').val('Show');
                    $('#action').val('Show');
                    $('#formModal').modal('show');
                }
            })
        });

        var user_id;

        $(document).on('click', '.delete', function() {
            user_id = $(this).attr('id');
            $('#confirmModal').modal('show');
        });

        $('#ok_button').click(function() {
            $.ajax({
                url: "sample/destroy/" + user_id,
                beforeSend: function() {
                    $('#ok_button').text('Deleting...');
                },
                success: function(data) {
                    setTimeout(function() {
                        $('#confirmModal').modal('hide');
                        $('#user_table').DataTable().ajax.reload();
                        alert('Data Deleted');
                    }, 2000);
                }
            })
        });

    });
</script>

resources/views/WD/view_detail.blade.php
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRUD</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>
    <div id="formModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add New User</h4>
            </div>
            <div class="modal-body">
                <span id="form_result"></span>
                <form method="post" id="sample_form" class="form-horizontal">
                    @csrf
                    <div class="form-group">
                        <label class="control-label col-md-4">user name: </label>
                        <div class="col-md-8">
                            <input type="text" name="user_name" id="user_name" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4">password: </label>
                        <div class="col-md-8">
                            <input type="password" name="password" id="password" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4">First Name : </label>
                        <div class="col-md-8">
                            <input type="text" name="first_name" id="first_name" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4">Last Name : </label>
                        <div class="col-md-8">
                            <input type="text" name="last_name" id="last_name" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4">Email: </label>
                        <div class="col-md-8">
                            <input type="text" name="email" id="email" class="form-control" />
                        </div>
                    </div>
                    <br />
                    <div class="form-group" align="center">
                        <input type="hidden" name="action" id="action" value="Add" />
                        <input type="hidden" name="hidden_id" id="hidden_id" />
                        <input type="submit" name="action_button" id="action_button" class="btn btn-warning" value="Add" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</body>

</html>